from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from src.ai.performance_tracker import TradePerformance
from src.backtesting.trade_simulator import (
    TradeRequest,
    TradeSimulator,
)


@dataclass(slots=True)
class CandleSignal:
    """
    Signal generated by a strategy.
    """

    symbol: str

    timeframe: str

    entry_price: float

    exit_price: float

    quantity: float

    strategy: str

    confidence: float

    duration_minutes: int

    risk_reward: float


class StrategyRunner:
    """
    Executes historical strategy signals.

    Responsibilities

    - Receive historical signals
    - Simulate trades
    - Produce TradePerformance list

    Future

    - Multi Strategy
    - Portfolio Simulation
    - Position Scaling
    """

    def __init__(
        self,
        simulator: TradeSimulator | None = None,
    ) -> None:

        self.simulator = simulator or TradeSimulator()

    # -----------------------------------------------------

    def run(
        self,
        signals: Iterable[CandleSignal],
    ) -> list[TradePerformance]:

        results: list[TradePerformance] = []

        for signal in signals:

            simulation = self.simulator.simulate(

                TradeRequest(
                    entry_price=signal.entry_price,
                    exit_price=signal.exit_price,
                    quantity=signal.quantity,
                )

            )

            results.append(

                TradePerformance(

                    strategy=signal.strategy,

                    symbol=signal.symbol,

                    timeframe=signal.timeframe,

                    pnl=simulation.net_profit,

                    risk_reward=signal.risk_reward,

                    win=simulation.net_profit > 0,

                    confidence=signal.confidence,

                    duration_minutes=signal.duration_minutes,

                )

            )

        return results