"""Single injectable synchronous transport boundary for BingX VST."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Protocol, runtime_checkable

from src.exchange.bingx_client import BingXHttpClient

from .models import RemoteBalance, RemoteFill, RemoteOrder, RemotePosition


@runtime_checkable
class VstTransport(Protocol):
    supports_protected_entry: bool

    def initialize(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def server_time_ms(self) -> int: ...
    def submit_order(self, request: Mapping[str, Any]) -> RemoteOrder: ...
    def query_order(self, symbol: str, client_order_id: str) -> RemoteOrder | None: ...
    def cancel_order(self, symbol: str, client_order_id: str) -> RemoteOrder: ...
    def fetch_orders(self) -> Sequence[RemoteOrder]: ...
    def fetch_fills(self, symbol: str | None = None) -> Sequence[RemoteFill]: ...
    def fetch_positions(self) -> Sequence[RemotePosition]: ...
    def fetch_balance(self) -> RemoteBalance: ...


def signing_string(parameters: Mapping[str, str]) -> str:
    """Reuse the frozen BingX canonical parameter ordering contract."""
    return BingXHttpClient._build_signing_string(parameters)


__all__ = ("VstTransport", "signing_string")
